with-expecter: true
dir: internal/mock
outpkg: mock
packages:
  github.com/Sokol111/educational-go/internal/repository:
    config:
    interfaces:
      UserRepository:
        config:
  github.com/Sokol111/educational-go/internal/repository/db:
    config:
    interfaces:
      Querier: