// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               int64
	Version          int32
	Name             string
	Enabled          bool
	CreatedDate      pgtype.Timestamp
	LastModifiedDate pgtype.Timestamp
}
